// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrepApi.Data;

#nullable disable

namespace PrepApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509183928_NormalizedSchema")]
    partial class NormalizedSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PrepApi.Models.Acta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActaId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("ArithmeticValidationOk")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AssignedQueue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ConfidenceLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<float>("GlobalConfidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("AssignedQueue");

                    b.HasIndex("IngestedAt");

                    b.HasIndex("Status");

                    b.ToTable("Actas");
                });

            modelBuilder.Entity("PrepApi.Models.ActaField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActaId")
                        .HasColumnType("int");

                    b.Property<string>("BoundingRegion")
                        .HasColumnType("longtext");

                    b.Property<float>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("ConfidenceLevel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActaId");

                    b.HasIndex("FieldName");

                    b.ToTable("ActaFields");
                });

            modelBuilder.Entity("PrepApi.Models.ActaValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Detail")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Passed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ActaId");

                    b.ToTable("ActaValidations");
                });

            modelBuilder.Entity("PrepApi.Models.ActaField", b =>
                {
                    b.HasOne("PrepApi.Models.Acta", "Acta")
                        .WithMany("Fields")
                        .HasForeignKey("ActaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acta");
                });

            modelBuilder.Entity("PrepApi.Models.ActaValidation", b =>
                {
                    b.HasOne("PrepApi.Models.Acta", "Acta")
                        .WithMany("Validations")
                        .HasForeignKey("ActaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acta");
                });

            modelBuilder.Entity("PrepApi.Models.Acta", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Validations");
                });
#pragma warning restore 612, 618
        }
    }
}
